//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StationeryCompany_WPF_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ФирмаКанцтоваровEntities : DbContext
    {
        public ФирмаКанцтоваровEntities()
            : base("name=ФирмаКанцтоваровEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Менеджеры> Менеджеры { get; set; }
        public virtual DbSet<Продажи> Продажи { get; set; }
        public virtual DbSet<Товары> Товары { get; set; }
        public virtual DbSet<Фирмы> Фирмы { get; set; }
    }
}
