//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StationeryCompany_WPF_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товары()
        {
            this.Продажи = new HashSet<Продажи>();
        }
    
        public int ТоварID { get; set; }
        public string Название { get; set; }
        public string Тип { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<decimal> Себестоимость { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продажи> Продажи { get; set; }

        //чтобы в выпадающем меню отражались товары, нужно переопределить метод ToString()
        public override string ToString()
        {
            return Название; // возвращает название товара
        }
    }
}
