//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StationeryCompany_WPF_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Менеджеры
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Менеджеры()
        {
            this.Продажи = new HashSet<Продажи>();
        }
    
        public int МенеджерID { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продажи> Продажи { get; set; }

        //чтобы в выпадающем меню отражались фамилии менеджеров, нужно переопределить метод ToString()
        public override string ToString()
        {
            return Фамилия; // возвращает имя менеджера
        }

    }
}
