//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StationeryCompany_WPF_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продажи
    {
        public int ПродажаID { get; set; }
        public Nullable<int> ТоварID { get; set; }
        public Nullable<int> МенеджерID { get; set; }
        public Nullable<int> ФирмаID { get; set; }
        public Nullable<int> КоличествоПроданных { get; set; }
        public Nullable<decimal> ЦенаЗаЕдиницу { get; set; }
        public Nullable<System.DateTime> ДатаПродажи { get; set; }
    
        public virtual Менеджеры Менеджеры { get; set; }
        public virtual Товары Товары { get; set; }
        public virtual Фирмы Фирмы { get; set; }

        public override string ToString()
        {
            string datePart = ДатаПродажи.HasValue ? ДатаПродажи.Value.ToString("dd.MM.yyyy") : "Дата не указана";
            return $"Продажа ID: {ПродажаID}, Дата: {datePart}";
        }


    }
}
