//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int IDbook { get; set; }
        public string BookTitle { get; set; }
        public Nullable<int> IDauthor { get; set; }
        public Nullable<int> NumberOfPagesRead { get; set; }
        public int NumberOfPages { get; set; }
        public int IDstatus { get; set; }
        public Nullable<int> Rating { get; set; }
        public byte[] Cover { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Status Status { get; set; }
    }
}
